{
  imports = [
    ./ai-tools.nix
    ./auto-locale.nix
    ./backup.nix
    ./boot-safeguard.nix
    ./central-configs-plan.nix
    ./config-merger.nix
    ./configs.nix
    ./defaults.nix
    ./fail2ban.nix
    ./firewall.nix
    ./hardware-configuration.nix
    ./home-manager.nix
    ./host.nix
    ./host-q958-hardware-configuration.nix
    ./host-q958-hardware-profile.nix
    ./kernel-slim.nix
    ./lib-helpers.nix
    ./lib-helpers-meta.nix
    ./locale.nix
    ./logging.nix
    ./motd.nix
    ./network.nix
    ./nix-tuning.nix
    ./ports.nix
    ./principles.nix
    ./registry.nix
    ./secrets.nix
    ./shell.nix
    ./shell-premium.nix
    ./ssh.nix
    ./ssh-rescue.nix
    ./symbiosis.nix
    ./system.nix
    ./system-stability.nix
    ./tty-info.nix
    ./user-moritz-home.nix
    ./user-preferences.nix
    ./users.nix
    ./zram-swap.nix
  ];
}