/**
 * ---
 * nms_version: 2.3
 * identity:
 *   id: NIXH-00-CORE-022
 *   title: "Secrets (SRE Hierarchical)"
 *   layer: 00
 * summary: Centralized secret management with sops-nix and hierarchical organization.
 * source_nixpkgs: https://github.com/Mic92/sops-nix
 * ---
 */
{ config, lib, ... }:
{
  config = {
    sops = {
      defaultSopsFile = ../secrets.yaml;
      defaultSopsFormat = "yaml";
      
      age = {
        sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
        keyFile = "/var/lib/sops-nix/key.txt";
        generateKey = true;
      };

      # ── HIERARCHISCHE GEHEIMNIS-DEFINITION ────────────────────────────────
      # Wir mappen die flachen Keys aus secrets.yaml auf logische Gruppen.
      secrets = {
        # Identity
        unraid_root_password = { owner = "root"; };
        ssh_github_key = { owner = "moritz"; };
        ssh_unraid_key = { owner = "moritz"; };
        
        # Infrastructure
        github_token = { };
        cloudflare_token = { };
        tailscale_token = { };
        wg_privado_private_key = { };
        
        # Apps: Media
        sonarr_api_key = { owner = "sonarr"; };
        radarr_api_key = { owner = "radarr"; };
        readarr_api_key = { owner = "readarr"; };
        sabnzbd_api_key = { owner = "sabnzbd"; };
        
        # Apps: Automation & Security
        n8n_enc_key = { owner = "n8n"; };
        vaultwarden_env = { };
        miniflux_admin_password = { };
        paperless_secret_key = { };
        readeck_env = { };
      };

      # ── SRE TEMPLATES (RAM-Disk only) ─────────────────────────────────────
      # Wir nutzen Templates, um strukturierte Config-Files im RAM zu erzeugen.
      templates."shared-runtime.env" = {
        owner = "moritz";
        mode = "0400";
        content = ''
          # Generated by NixOS SRE Secrets Module
          GITHUB_TOKEN="${config.sops.placeholder.github_token}"
          CLOUDFLARE_TOKEN="${config.sops.placeholder.cloudflare_token}"
          TAILSCALE_TOKEN="${config.sops.placeholder.tailscale_token}"
          SONARR_API_KEY="${config.sops.placeholder.sonarr_api_key}"
          RADARR_API_KEY="${config.sops.placeholder.radarr_api_key}"
          UNRAID_PASS="${config.sops.placeholder.unraid_root_password}"
        '';
      };
    };
  };

  # ── ÖFFENTLICHE API FÜR ANDERE MODULE ─────────────────────────────────────
  options.my.secrets = {
    files = {
      sharedEnv = lib.mkOption { 
        type = lib.types.path; 
        default = config.sops.templates."shared-runtime.env".path;
      };
      sshGithubKey = lib.mkOption { 
        type = lib.types.path; 
        default = config.sops.secrets.ssh_github_key.path; 
      };
    };
  };
}
/**
 * technical_integrity:
 *   eof_marker: NIXHOME_VALID_EOF
 */
