/**
 * ---
 * nms_version: 2.3
 * identity:
 *   id: NIXH-00-CORE-022
 *   title: "Secrets (SRE Hierarchical v2)"
 *   layer: 00
 * summary: Advanced hierarchical secret management with RAM-only templates and TPM support info.
 * source_nixpkgs: https://github.com/Mic92/sops-nix
 * ---
 */
{ config, lib, pkgs, ... }:
{
  config = {
    sops = {
      defaultSopsFile = ../secrets.yaml;
      defaultSopsFormat = "yaml";
      
      # ── ENTSCHLÜSSELUNGS-ANKER ──────────────────────────────────────────
      # SRE: Wir nutzen den SSH-Host-Key. Das ist so sicher wie TPM, da der Key 
      # physisch an die Installation auf diesem Mainboard gebunden ist.
      age = {
        sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
        keyFile = "/var/lib/sops-nix/key.txt";
        generateKey = true;
      };

      # 💡 TIPP: Falls du echte Hardware-Bindung via TPM willst:
      # 1. 'age-plugin-tpm' installieren.
      # 2. Key generieren: 'age-plugin-tpm --generate -o /var/lib/sops-nix/tpm-key.txt'
      # 3. Den Public-Key in '.sops.yaml' eintragen.

      secrets = {
        # Identity
        "identity/unraid_root_password" = { owner = "root"; };
        "identity/ssh_github_key" = { owner = "moritz"; };
        "identity/ssh_unraid_key" = { owner = "moritz"; };
        
        # Infrastructure
        # 🔗 Cloudflare: https://dash.cloudflare.com/profile/api-tokens
        "infra/github_token" = { };
        "infra/cloudflare_token" = { };
        "infra/tailscale_token" = { }; # 🔗 Tailscale: https://login.tailscale.com/admin/settings/keys
        "infra/wg_privado_private_key" = { };
        
        # Apps: Media
        "apps/media/sonarr_api_key" = { owner = "sonarr"; };
        "apps/media/radarr_api_key" = { owner = "radarr"; };
        "apps/media/readarr_api_key" = { owner = "readarr"; };
        "apps/media/sabnzbd_api_key" = { owner = "sabnzbd"; };
        
        # Apps: Automation & Security
        "apps/automation/n8n_enc_key" = { owner = "n8n"; };
        "apps/security/vaultwarden_env" = { };
        "apps/security/miniflux_admin_pass" = { };
        "apps/security/paperless_secret" = { };
        "apps/security/readeck_env" = { };
      };

      # ── SRE RAM-TEMPLATES ──────────────────────────────────────────────────
      templates."shared-runtime.env" = {
        owner = "moritz";
        mode = "0400";
        content = ''
          # Generated by NixOS SRE Secrets Module
          # 🔗 GitHub Tokens: https://github.com/settings/tokens
          GITHUB_TOKEN="${config.sops.placeholder."infra/github_token"}"
          CLOUDFLARE_TOKEN="${config.sops.placeholder."infra/cloudflare_token"}"
          TAILSCALE_TOKEN="${config.sops.placeholder."infra/tailscale_token"}"
          UNRAID_PASS="${config.sops.placeholder."identity/unraid_root_password"}"
        '';
      };

      templates."media-stack.env" = {
        owner = "root";
        group = "media";
        mode = "0440";
        content = ''
          SONARR_API_KEY="${config.sops.placeholder."apps/media/sonarr_api_key"}"
          RADARR_API_KEY="${config.sops.placeholder."apps/media/radarr_api_key"}"
          READARR_API_KEY="${config.sops.placeholder."apps/media/readarr_api_key"}"
          SABNZBD_API_KEY="${config.sops.placeholder."apps/media/sabnzbd_api_key"}"
        '';
      };
    };
  };

  environment.systemPackages = [ pkgs.age-plugin-tpm ];

  options.my.secrets = {
    files = {
      sharedEnv = lib.mkOption { 
        type = lib.types.path; 
        default = config.sops.templates."shared-runtime.env".path;
      };
      mediaEnv = lib.mkOption { 
        type = lib.types.path; 
        default = config.sops.templates."media-stack.env".path;
      };
    };
  };
}
/**
 * technical_integrity:
 *   eof_marker: NIXHOME_VALID_EOF
 */
